-- Run this in the Supabase SQL editor before enabling the admin dashboard.

create table if not exists public.live_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'MR MOIN Admin',
  created_at timestamptz not null default now()
);

alter table public.live_admins enable row level security;
drop policy if exists "Admins can read their own admin record" on public.live_admins;

create policy "Admins can read their own admin record"
on public.live_admins for select
to authenticated
using (user_id = auth.uid());

create table if not exists public.live_questions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  question text not null,
  status text not null default 'approved' check (status in ('pending', 'approved', 'archived')),
  created_at timestamptz not null default now()
);

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  event_type text not null check (event_type in ('page_view', 'live_join', 'live_leave')),
  page_path text not null,
  page_title text,
  referrer text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.project_inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text,
  service text,
  message text not null,
  status text not null default 'new' check (status in ('new', 'contacted', 'in_progress', 'completed', 'archived')),
  created_at timestamptz not null default now()
);

alter table public.project_inquiries enable row level security;
drop policy if exists "Anyone can submit project inquiries" on public.project_inquiries;
drop policy if exists "Admins can read project inquiries" on public.project_inquiries;
drop policy if exists "Admins can update project inquiries" on public.project_inquiries;

create policy "Anyone can submit project inquiries"
on public.project_inquiries for insert
with check (true);

create policy "Admins can read project inquiries"
on public.project_inquiries for select
using (
  exists (
    select 1 from public.live_admins
    where public.live_admins.user_id = auth.uid()
  )
);

create policy "Admins can update project inquiries"
on public.project_inquiries for update
using (
  exists (
    select 1 from public.live_admins
    where public.live_admins.user_id = auth.uid()
  )
);

-- The live_questions table is used by live.js. These policies keep public
-- submissions possible while limiting reads and moderation to live admins.
alter table public.live_questions enable row level security;
alter table public.site_events enable row level security;
drop policy if exists "Anyone can submit live questions" on public.live_questions;
drop policy if exists "Anyone can read approved live questions" on public.live_questions;
drop policy if exists "Admins can update live questions" on public.live_questions;
drop policy if exists "Anyone can submit site events" on public.site_events;
drop policy if exists "Admins can read site events" on public.site_events;

create policy "Anyone can submit live questions"
on public.live_questions for insert
with check (true);

create policy "Anyone can read approved live questions"
on public.live_questions for select
using (status = 'approved' or exists (
  select 1 from public.live_admins
  where public.live_admins.user_id = auth.uid()
));

create policy "Admins can update live questions"
on public.live_questions for update
using (
  exists (
    select 1 from public.live_admins
    where public.live_admins.user_id = auth.uid()
  )
);

create policy "Anyone can submit site events"
on public.site_events for insert
with check (true);

create policy "Admins can read site events"
on public.site_events for select
using (
  exists (
    select 1 from public.live_admins
    where public.live_admins.user_id = auth.uid()
  )
);
